name: Build UniversalPerformance dylib

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:

  build:

    runs-on: macos-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v4


    - name: Build dylib
      run: |
        make


    - name: Sign dylib
      run: |
        codesign \
        --force \
        --sign - \
        --timestamp=none \
        UniversalPerformance.dylib


    - name: Verify signature
      run: |
        codesign --verify --verbose UniversalPerformance.dylib
        codesign -dv UniversalPerformance.dylib


    - name: Package
      run: |
        mkdir output
        cp UniversalPerformance.dylib output/


    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: UniversalPerformance-signed
        path: output
